imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ VipCreditAdminBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: vipcredit
        connections:
            vipcredit:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

vip_credit_admin:
    admin_submenu:
        custom:
            id: custom
            name: 常用
            icon: NULL
            tip: NULL
            parent: root
            top: ''
            items:
                custom_set:
                    id: custom_set
                    name: 常用菜单
                    icon: NULL
                    tip: NULL
                    parent: custom
                    top: NULL
                    url: vip_credit_admin_custom
        article:
            id: article
            name: 图文编辑
            icon: NULL
            tip: NULL
            parent: root
            top: ''
            items:
                article_category:
                    id: article_category
                    name: 图文类别
                    icon: NULL
                    tip: NULL
                    parent: article
                    top: NULL
                    url: vip_credit_admin_article_category
                article_list:
                    id: article_list
                    name: 文章列表
                    icon: NULL
                    tip: NULL
                    parent: article
                    top: NULL
                    url: vip_credit_admin_article_list


