vip_credit_admin:
    resource: "@VipCreditAdminBundle/Resources/config/routing.php"
    prefix:   /admin

vip_credit_order:
    resource: "@VipCreditOrderBundle/Resources/config/routing.php"
    prefix:   /order

